_BASE_: FastInst_table_tennis_Base.yaml
MODEL:
  BACKBONE: 
    NAME: "build_resnest_backbone"
  # WEIGHTS: "output/table_tennis/fastinst_s50_T4_GN_gelu_E2_0319/model_0064999.pth" #inference
  WEIGHTS: "output/table_tennis/22_fastinst_s50_T5_CA_0418/model_0017499.pth"
  RESNETS:
    DEPTH: 50
  FASTINST:
    DEC_LAYERS: 5 
OUTPUT_DIR: "output/table_tennis/22_fastinst_s50_T5_CA_0418"
