_BASE_: FastInst_table_tennis_Base.yaml
MODEL:
  BACKBONE: 
    NAME: "build_resnet_backbone"
  
  # WEIGHTS: "R-101.pkl"
  WEIGHTS: "output/table_tennis/2_fastinst_R101_table_tennis_0219/model_final.pth"
  RESNETS:
    DEPTH: 101
  FASTINST:
    DEC_LAYERS: 5
OUTPUT_DIR: "output/fastinst_R101_table_tennis_0219"
